version: '3.9'

services:

  app:
    build: ./app
    container_name: app
    tty: true
    ports:
      - 12000:3000
    volumes:
      - ./app:/var/www
    networks:
      - default
    command: sh -c "yarn start"
